sonar.projectKey=epms-adam
sonar.projectName=EPMS / ADAM
sonar.sourceEncoding=UTF-8
sonar.sources=apps/server/src,apps/desktop/src,packages/shared/src
sonar.exclusions=**/dist/**,**/dist-electron/**,**/node_modules/**,**/release/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
