import { ProcedureStatus } from "@epms/shared";
import { ProcedureModel } from "../models/Procedure.model";
import { DepartmentModel } from "../models/Department.model";
import { CategoryModel } from "../models/Category.model";
import { UserModel } from "../models/User.model";

interface ProcedureSeedDef {
  title: string;
  description: string;
  department: string;
  category: string;
  responsiblePerson: string;
  keywords: string[];
  requiredDocuments: string[];
  steps: string[];
  status: ProcedureStatus;
  versionNumber: string;
  daysAgo: number;
}

const DEFS: ProcedureSeedDef[] = [
  {
    title: "Student Enrollment",
    description: "Process for newly admitted students to enroll at ESPRIT for the first time.",
    department: "Academic Affairs",
    category: "Student Enrollment",
    responsiblePerson: "Registrar's Office",
    keywords: ["enrollment", "new student", "admission"],
    requiredDocuments: ["Baccalaureate certificate", "National ID copy", "4 ID photos"],
    steps: [
      "Submit the online enrollment form",
      "Upload required documents",
      "Pay the enrollment fee",
      "Receive student ID and enrollment confirmation",
    ],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "2.0",
    daysAgo: 210,
  },
  {
    title: "Annual Registration",
    description: "Yearly course and tuition registration for continuing students.",
    department: "Academic Affairs",
    category: "Annual Registration",
    responsiblePerson: "Registrar's Office",
    keywords: ["registration", "annual", "courses"],
    requiredDocuments: ["Previous year transcript", "Tuition payment receipt"],
    steps: ["Confirm course selection", "Validate with academic advisor", "Pay tuition", "Print registration certificate"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.3",
    daysAgo: 160,
  },
  {
    title: "Re-registration",
    description: "Registration procedure for students repeating a year.",
    department: "Academic Affairs",
    category: "Re-registration",
    responsiblePerson: "Registrar's Office",
    keywords: ["re-registration", "repeat year"],
    requiredDocuments: ["Academic committee decision", "Tuition payment receipt"],
    steps: ["Submit re-registration request", "Academic committee review", "Pay adjusted tuition"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.0",
    daysAgo: 140,
  },
  {
    title: "Transfer Request",
    description: "Procedure for students requesting transfer between specialties or campuses.",
    department: "Academic Affairs",
    category: "Transfer Request",
    responsiblePerson: "Academic Affairs Office",
    keywords: ["transfer", "specialty change", "campus"],
    requiredDocuments: ["Transfer request letter", "Current transcript"],
    steps: ["Submit transfer request", "Department head approval", "Update student file"],
    status: ProcedureStatus.DRAFT,
    versionNumber: "0.9",
    daysAgo: 12,
  },
  {
    title: "Graduation Process",
    description: "Final steps for students completing all graduation requirements.",
    department: "Academic Affairs",
    category: "Graduation Process",
    responsiblePerson: "Registrar's Office",
    keywords: ["graduation", "diploma"],
    requiredDocuments: ["Final transcript", "PFE validation certificate", "Cleared library/finance status"],
    steps: [
      "Verify all academic requirements are met",
      "Clear financial and library holds",
      "Submit diploma request",
      "Attend graduation ceremony",
    ],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.5",
    daysAgo: 95,
  },
  {
    title: "Internship Validation",
    description: "Validation of mandatory internship reports and supervisor evaluations.",
    department: "Internship Office",
    category: "Internship Validation",
    responsiblePerson: "Internship Coordinator",
    keywords: ["internship", "validation", "report"],
    requiredDocuments: ["Internship report", "Company evaluation form", "Attendance certificate"],
    steps: ["Submit internship report", "Supervisor evaluation", "Jury defense", "Final grade recorded"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.2",
    daysAgo: 70,
  },
  {
    title: "PFE Validation",
    description: "End-of-studies project (PFE) submission, defense, and validation process.",
    department: "Academic Affairs",
    category: "PFE Validation",
    responsiblePerson: "PFE Coordinator",
    keywords: ["PFE", "final project", "defense"],
    requiredDocuments: ["PFE report", "Company agreement", "Jury evaluation sheet"],
    steps: [
      "Submit PFE topic for approval",
      "Submit final PFE report",
      "Schedule defense with jury",
      "Record final grade and validate diploma eligibility",
    ],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "2.1",
    daysAgo: 55,
  },
  {
    title: "Scholarship Request",
    description: "Application process for merit-based and need-based scholarships.",
    department: "Student Affairs",
    category: "Scholarship Request",
    responsiblePerson: "Student Affairs Office",
    keywords: ["scholarship", "financial aid", "merit"],
    requiredDocuments: ["Transcript", "Income certificate", "Scholarship application form"],
    steps: ["Submit application form", "Attach supporting documents", "Committee review", "Award notification"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.1",
    daysAgo: 130,
  },
  {
    title: "Grade Appeal",
    description: "Procedure for students to formally contest a final exam grade.",
    department: "Examination Department",
    category: "Grade Appeal",
    responsiblePerson: "Examination Office",
    keywords: ["grade", "appeal", "contest"],
    requiredDocuments: ["Appeal request form", "Copy of graded exam (if available)"],
    steps: ["Submit appeal within 5 days of result publication", "Re-grading by second examiner", "Final decision notified"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.0",
    daysAgo: 40,
  },
  {
    title: "Retake Exams",
    description: "Organization of retake examination sessions for failed modules.",
    department: "Examination Department",
    category: "Retake Exams",
    responsiblePerson: "Examination Office",
    keywords: ["retake", "exam", "session"],
    requiredDocuments: ["Retake registration form"],
    steps: ["Register for retake session", "Pay retake fee if applicable", "Sit the exam", "Result published"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.0",
    daysAgo: 88,
  },
  {
    title: "Exam Planning",
    description: "Annual scheduling of examination sessions across all departments.",
    department: "Examination Department",
    category: "Exam Planning",
    responsiblePerson: "Examination Office",
    keywords: ["exam", "schedule", "planning"],
    requiredDocuments: ["Course list", "Room availability list"],
    steps: ["Collect course lists from departments", "Allocate rooms and time slots", "Publish exam calendar"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.4",
    daysAgo: 175,
  },
  {
    title: "Invigilator Assignment",
    description: "Assignment of faculty and staff as exam invigilators.",
    department: "Examination Department",
    category: "Invigilator Assignment",
    responsiblePerson: "Examination Office",
    keywords: ["invigilator", "exam staff"],
    requiredDocuments: ["Faculty availability form"],
    steps: ["Collect faculty availability", "Assign invigilators per room", "Notify assigned staff"],
    status: ProcedureStatus.DRAFT,
    versionNumber: "0.8",
    daysAgo: 8,
  },
  {
    title: "Grade Submission",
    description: "Procedure for faculty to submit final module grades.",
    department: "Examination Department",
    category: "Grade Submission",
    responsiblePerson: "Examination Office",
    keywords: ["grades", "submission", "faculty"],
    requiredDocuments: ["Grade sheet template"],
    steps: ["Faculty submits grades via portal", "Department head validation", "Grades locked for publication"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.2",
    daysAgo: 60,
  },
  {
    title: "Result Publication",
    description: "Official publication of examination results to students.",
    department: "Examination Department",
    category: "Result Publication",
    responsiblePerson: "Examination Office",
    keywords: ["results", "publication"],
    requiredDocuments: [],
    steps: ["Validate all grades are submitted", "Publish results on student portal", "Open appeal window"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.0",
    daysAgo: 45,
  },
  {
    title: "Fraud Reporting",
    description: "Procedure for reporting suspected academic fraud during examinations.",
    department: "Examination Department",
    category: "Fraud Reporting",
    responsiblePerson: "Examination Office",
    keywords: ["fraud", "reporting", "exam incident"],
    requiredDocuments: ["Incident report form"],
    steps: ["Invigilator files incident report", "Submit to disciplinary committee", "Investigation opened"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.0",
    daysAgo: 100,
  },
  {
    title: "Disciplinary Committee",
    description: "Convening and conducting disciplinary committee hearings for fraud cases.",
    department: "Examination Department",
    category: "Disciplinary Committee",
    responsiblePerson: "Disciplinary Committee Chair",
    keywords: ["disciplinary", "committee", "hearing"],
    requiredDocuments: ["Investigation report", "Student statement"],
    steps: ["Schedule hearing", "Hear student and witnesses", "Committee deliberation", "Sanction decision issued"],
    status: ProcedureStatus.ARCHIVED,
    versionNumber: "1.0",
    daysAgo: 300,
  },
  {
    title: "Certificate Request",
    description: "Request process for official enrollment and attendance certificates.",
    department: "Administration",
    category: "Certificate Request",
    responsiblePerson: "Administration Office",
    keywords: ["certificate", "attestation"],
    requiredDocuments: ["Request form", "Student ID"],
    steps: ["Submit request form", "Pay administrative fee", "Collect certificate within 3 business days"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.0",
    daysAgo: 50,
  },
  {
    title: "Transcript Request",
    description: "Request process for official academic transcripts.",
    department: "Administration",
    category: "Transcript Request",
    responsiblePerson: "Administration Office",
    keywords: ["transcript", "academic record"],
    requiredDocuments: ["Request form"],
    steps: ["Submit request online or in person", "Pay fee", "Collect or receive by mail"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.1",
    daysAgo: 35,
  },
  {
    title: "Student Card Request",
    description: "Issuance and replacement of student ID cards.",
    department: "Administration",
    category: "Student Card Request",
    responsiblePerson: "Administration Office",
    keywords: ["student card", "ID"],
    requiredDocuments: ["Photo", "Loss declaration (if replacement)"],
    steps: ["Submit request", "Pay replacement fee if applicable", "Card issued within 5 business days"],
    status: ProcedureStatus.DRAFT,
    versionNumber: "0.5",
    daysAgo: 5,
  },
  {
    title: "Archive Consultation",
    description: "Procedure for consulting archived academic and administrative records.",
    department: "Library",
    category: "Archive Consultation",
    responsiblePerson: "Library Staff",
    keywords: ["archive", "records", "consultation"],
    requiredDocuments: ["Consultation request form"],
    steps: ["Submit consultation request", "Approval by archive officer", "Supervised access granted"],
    status: ProcedureStatus.ARCHIVED,
    versionNumber: "1.0",
    daysAgo: 320,
  },
  {
    title: "Tuition Payment",
    description: "Standard procedure for paying semester tuition fees.",
    department: "Finance",
    category: "Tuition Payment",
    responsiblePerson: "Finance Office",
    keywords: ["tuition", "payment"],
    requiredDocuments: ["Payment slip"],
    steps: ["Choose payment method", "Pay full or partial tuition", "Receive payment receipt"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.3",
    daysAgo: 150,
  },
  {
    title: "Installment Plan",
    description: "Setting up a tuition payment installment plan.",
    department: "Finance",
    category: "Installment Plan",
    responsiblePerson: "Finance Office",
    keywords: ["installment", "payment plan"],
    requiredDocuments: ["Installment request form", "Income proof"],
    steps: ["Submit installment request", "Finance office approval", "Sign installment agreement"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.0",
    daysAgo: 120,
  },
  {
    title: "Refund Request",
    description: "Procedure for requesting a tuition or fee refund.",
    department: "Finance",
    category: "Refund Request",
    responsiblePerson: "Finance Office",
    keywords: ["refund", "reimbursement"],
    requiredDocuments: ["Refund request form", "Original payment receipt"],
    steps: ["Submit refund request", "Finance review", "Refund processed within 15 business days"],
    status: ProcedureStatus.DRAFT,
    versionNumber: "0.7",
    daysAgo: 3,
  },
  {
    title: "Employee Recruitment",
    description: "End-to-end hiring process for new faculty and staff positions.",
    department: "Human Resources",
    category: "Employee Recruitment",
    responsiblePerson: "HR Manager",
    keywords: ["recruitment", "hiring"],
    requiredDocuments: ["Job requisition form", "Candidate CV", "Interview evaluation sheet"],
    steps: ["Approve job requisition", "Post vacancy", "Screen and interview candidates", "Issue offer letter"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.2",
    daysAgo: 110,
  },
  {
    title: "Onboarding",
    description: "Onboarding checklist for new employees joining ESPRIT.",
    department: "Human Resources",
    category: "Onboarding",
    responsiblePerson: "HR Manager",
    keywords: ["onboarding", "new hire"],
    requiredDocuments: ["Signed contract", "ID documents"],
    steps: ["Complete administrative paperwork", "IT account setup", "Department orientation", "30-day check-in"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.0",
    daysAgo: 75,
  },
  {
    title: "Leave Request",
    description: "Procedure for requesting annual, sick, or unpaid leave.",
    department: "Human Resources",
    category: "Leave Request",
    responsiblePerson: "HR Manager",
    keywords: ["leave", "vacation", "absence"],
    requiredDocuments: ["Leave request form", "Medical certificate (if sick leave)"],
    steps: ["Submit leave request via portal", "Manager approval", "HR records leave balance"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.4",
    daysAgo: 20,
  },
  {
    title: "Performance Evaluation",
    description: "Annual employee performance review process.",
    department: "Human Resources",
    category: "Performance Evaluation",
    responsiblePerson: "HR Manager",
    keywords: ["performance", "evaluation", "review"],
    requiredDocuments: ["Self-assessment form", "Manager evaluation form"],
    steps: ["Employee self-assessment", "Manager review meeting", "HR finalizes evaluation record"],
    status: ProcedureStatus.DRAFT,
    versionNumber: "0.6",
    daysAgo: 15,
  },
  {
    title: "Equipment Request",
    description: "Requesting office or classroom equipment from logistics.",
    department: "Logistics",
    category: "Equipment Request",
    responsiblePerson: "Logistics Office",
    keywords: ["equipment", "request"],
    requiredDocuments: ["Equipment request form"],
    steps: ["Submit request", "Logistics approval", "Equipment delivered or installed"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.0",
    daysAgo: 65,
  },
  {
    title: "Classroom Reservation",
    description: "Booking classrooms or amphitheaters for events and extra sessions.",
    department: "Logistics",
    category: "Classroom Reservation",
    responsiblePerson: "Logistics Office",
    keywords: ["classroom", "reservation", "booking"],
    requiredDocuments: ["Reservation request form"],
    steps: ["Check room availability", "Submit reservation request", "Confirmation issued"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.1",
    daysAgo: 30,
  },
  {
    title: "Vehicle Reservation",
    description: "Booking ESPRIT vehicles for official trips and events.",
    department: "Logistics",
    category: "Vehicle Reservation",
    responsiblePerson: "Logistics Office",
    keywords: ["vehicle", "transport", "booking"],
    requiredDocuments: ["Trip request form", "Valid driving license"],
    steps: ["Submit trip request", "Logistics approval", "Vehicle and driver assigned"],
    status: ProcedureStatus.ARCHIVED,
    versionNumber: "1.0",
    daysAgo: 280,
  },
  {
    title: "User Account Creation",
    description: "Creating new IT accounts (email, portal, Wi-Fi) for students and staff.",
    department: "IT Department",
    category: "User Account Creation",
    responsiblePerson: "IT Support Team",
    keywords: ["account", "IT", "credentials"],
    requiredDocuments: ["Account request form"],
    steps: ["Submit account request", "IT provisions account", "Credentials sent to user"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.0",
    daysAgo: 90,
  },
  {
    title: "Password Reset",
    description: "Self-service and assisted password reset procedure for institutional accounts.",
    department: "IT Department",
    category: "Password Reset",
    responsiblePerson: "IT Support Team",
    keywords: ["password", "reset", "account"],
    requiredDocuments: [],
    steps: ["Use self-service reset portal", "If locked out, contact IT helpdesk with ID", "New password issued"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.2",
    daysAgo: 18,
  },
  {
    title: "Software Request",
    description: "Requesting installation or licensing of software for academic or admin use.",
    department: "IT Department",
    category: "Software Request",
    responsiblePerson: "IT Support Team",
    keywords: ["software", "license", "installation"],
    requiredDocuments: ["Software request form"],
    steps: ["Submit request with justification", "IT and budget approval", "Software installed/licensed"],
    status: ProcedureStatus.DRAFT,
    versionNumber: "0.4",
    daysAgo: 6,
  },
  {
    title: "Security Incident Reporting",
    description: "Reporting and escalation procedure for IT security incidents.",
    department: "Security",
    category: "Security Incident Reporting",
    responsiblePerson: "Security Office",
    keywords: ["security", "incident", "reporting"],
    requiredDocuments: ["Incident report form"],
    steps: ["Report incident immediately to IT/security", "Initial containment", "Investigation and resolution report"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.0",
    daysAgo: 48,
  },
  {
    title: "Building Access",
    description: "Procedure for granting building and campus access badges.",
    department: "Security",
    category: "Building Access",
    responsiblePerson: "Security Office",
    keywords: ["access", "badge", "building"],
    requiredDocuments: ["Access request form", "ID photo"],
    steps: ["Submit access request", "Security approval", "Badge issued and activated"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.1",
    daysAgo: 200,
  },
  {
    title: "Safety Inspection",
    description: "Periodic safety inspection of campus facilities and labs.",
    department: "Facilities Management",
    category: "Safety Inspection",
    responsiblePerson: "Facilities Manager",
    keywords: ["safety", "inspection", "facilities"],
    requiredDocuments: ["Inspection checklist"],
    steps: ["Schedule inspection", "Conduct walkthrough with checklist", "File report and follow up on issues"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.0",
    daysAgo: 38,
  },
  {
    title: "Supplier Registration",
    description: "Registering a new supplier in the approved vendor list.",
    department: "Purchasing",
    category: "Supplier Registration",
    responsiblePerson: "Purchasing Office",
    keywords: ["supplier", "vendor", "registration"],
    requiredDocuments: ["Company registration certificate", "Tax identification"],
    steps: ["Submit supplier application", "Document verification", "Vendor approved and listed"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.0",
    daysAgo: 165,
  },
  {
    title: "Purchase Request",
    description: "Internal procedure for requesting the purchase of goods or services.",
    department: "Procurement",
    category: "Purchase Request",
    responsiblePerson: "Procurement Office",
    keywords: ["purchase", "request", "procurement"],
    requiredDocuments: ["Purchase request form", "Budget approval"],
    steps: ["Submit purchase request", "Budget validation", "Forward to purchase order creation"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.3",
    daysAgo: 25,
  },
  {
    title: "Purchase Order Creation",
    description: "Creating and issuing a purchase order to an approved supplier.",
    department: "Procurement",
    category: "Purchase Order Creation",
    responsiblePerson: "Procurement Office",
    keywords: ["purchase order", "supplier"],
    requiredDocuments: ["Approved purchase request"],
    steps: ["Select approved supplier", "Generate purchase order", "Send to supplier and track delivery"],
    status: ProcedureStatus.DRAFT,
    versionNumber: "0.9",
    daysAgo: 10,
  },
  {
    title: "Internal Audit",
    description: "Periodic internal audit of administrative and academic processes.",
    department: "Quality Assurance",
    category: "Internal Audit",
    responsiblePerson: "Quality Office",
    keywords: ["audit", "quality", "compliance"],
    requiredDocuments: ["Audit plan", "Audit checklist"],
    steps: ["Plan audit scope", "Conduct audit interviews and review", "Issue audit report with findings"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.1",
    daysAgo: 145,
  },
  {
    title: "Accreditation Process",
    description: "Coordinating institutional and program accreditation renewals.",
    department: "Quality Assurance",
    category: "Accreditation Process",
    responsiblePerson: "Quality Office",
    keywords: ["accreditation", "quality"],
    requiredDocuments: ["Self-evaluation report", "Supporting evidence portfolio"],
    steps: ["Prepare self-evaluation report", "Host accreditation site visit", "Address recommendations"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.0",
    daysAgo: 250,
  },
  {
    title: "Satisfaction Surveys",
    description: "Administering periodic student and staff satisfaction surveys.",
    department: "Quality Assurance",
    category: "Satisfaction Surveys",
    responsiblePerson: "Quality Office",
    keywords: ["survey", "satisfaction", "feedback"],
    requiredDocuments: [],
    steps: ["Design survey", "Distribute to target population", "Analyze results and publish summary"],
    status: ProcedureStatus.PUBLISHED,
    versionNumber: "1.0",
    daysAgo: 80,
  },
];

function randomViewCount(status: ProcedureStatus) {
  if (status === ProcedureStatus.PUBLISHED) return Math.floor(Math.random() * 220) + 10;
  if (status === ProcedureStatus.ARCHIVED) return Math.floor(Math.random() * 60);
  return Math.floor(Math.random() * 5);
}

export async function seedProcedures() {
  const [departments, categories, admin] = await Promise.all([
    DepartmentModel.find(),
    CategoryModel.find(),
    UserModel.findOne({ role: "super_admin" }),
  ]);

  if (!admin) {
    console.warn("[seed] no super admin found, skipping procedure seed");
    return [];
  }

  const departmentByName = new Map(departments.map((d) => [d.name, d]));
  const categoryByName = new Map(categories.map((c) => [c.name, c]));

  const results = [];
  for (const def of DEFS) {
    const department = departmentByName.get(def.department);
    const category = categoryByName.get(def.category);
    if (!department || !category) {
      console.warn(`[seed] skipping "${def.title}" — missing department/category reference`);
      continue;
    }

    const createdAt = new Date(Date.now() - def.daysAgo * 24 * 60 * 60 * 1000);
    const updatedAt = new Date(createdAt.getTime() + Math.floor(Math.random() * 10) * 24 * 60 * 60 * 1000);

    const procedure = await ProcedureModel.findOneAndUpdate(
      { title: def.title },
      {
        title: def.title,
        description: def.description,
        department: department._id,
        category: category._id,
        keywords: def.keywords,
        requiredDocuments: def.requiredDocuments,
        steps: def.steps.map((description, index) => ({ order: index + 1, description })),
        responsiblePerson: def.responsiblePerson,
        effectiveDate: createdAt,
        lastUpdate: updatedAt,
        // Seed data represents the initial, unmodified publication.
        versionNumber: "1.0",
        status: def.status,
        viewCount: randomViewCount(def.status),
        createdBy: admin._id,
      },
      { upsert: true, new: true }
    );

    await ProcedureModel.collection.updateOne(
      { _id: procedure._id },
      { $set: { createdAt, updatedAt } }
    );

    results.push(procedure);
  }

  console.log(`[seed] ${results.length} procedures ready`);
  return results;
}
