import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { ProcedureStatus, Role } from "@epms/shared";
import { Button } from "../../components/ui/Button";
import { Card } from "../../components/ui/Card";
import { StatusBadge } from "../../components/ui/Badge";
import { useProcedure } from "../../hooks/useProcedures";
import { useAuthStore } from "../../store/auth.store";
import { AttachmentsCard } from "../../components/procedures/AttachmentsCard";
import { AiAssistantCard } from "../../components/procedures/AiAssistantCard";
import { ProcedureRecommendations } from "../../components/procedures/ProcedureRecommendations";
import { ProcedureWorkflowTimeline } from "../../components/procedures/ProcedureWorkflowTimeline";
import { VersionHistory } from "../../components/procedures/VersionHistory";
import { WorkflowActions } from "../../components/procedures/WorkflowActions";
import { LinkifiedText } from "../../components/ui/LinkifiedText";
import { useRecentProceduresStore } from "../../store/recentProcedures.store";
import { ChecklistButton } from "../../components/procedures/ChecklistButton";

type Tab = "overview" | "steps" | "documents" | "versions" | "validation" | "recommendations" | "ai";
const tabs: Array<{ id: Tab; label: string }> = [
  { id: "overview", label: "Vue d’ensemble" }, { id: "steps", label: "Étapes" }, { id: "documents", label: "Documents" },
  { id: "versions", label: "Versions" }, { id: "validation", label: "Validation" }, { id: "recommendations", label: "Associées" },   { id: "ai", label: "Copilot" },
];
function readableDate(value?: string) { return value ? new Date(value).toLocaleDateString("fr-FR", { day: "2-digit", month: "short", year: "numeric" }) : undefined; }
function Skeleton() { return <div className="mx-auto max-w-7xl space-y-6"><div className="h-36 animate-pulse rounded-2xl bg-slate-100 dark:bg-slate-800" /><div className="h-12 animate-pulse rounded-xl bg-slate-100 dark:bg-slate-800" /><div className="grid gap-6 lg:grid-cols-[1fr_280px]"><div className="h-80 animate-pulse rounded-2xl bg-slate-100 dark:bg-slate-800" /><div className="h-80 animate-pulse rounded-2xl bg-slate-100 dark:bg-slate-800" /></div></div>; }

export default function ProcedureViewerPage() {
  const { id } = useParams<{ id: string }>(); const navigate = useNavigate(); const role = useAuthStore((state) => state.user?.role);
  const { data: procedure, isLoading, isError } = useProcedure(id); const [tab, setTab] = useState<Tab>("overview");
  const remember = useRecentProceduresStore((state) => state.remember);
  useEffect(() => { if (procedure) remember(procedure); }, [procedure, remember]);
  if (isLoading) return <Skeleton />;
  if (isError || !procedure) return <div className="mx-auto max-w-3xl rounded-xl border border-red-200 bg-red-50 p-6 text-sm text-red-700 dark:border-red-900 dark:bg-red-950/30 dark:text-red-300"><h1 className="font-semibold">Procédure indisponible</h1><p className="mt-1">Cette procédure n’existe plus ou vous n’êtes pas autorisé à la consulter.</p><Button variant="ghost" size="sm" className="mt-4" onClick={() => navigate("/procedures")}>Retour aux procédures</Button></div>;
  // Populated references can be null for legacy procedures whose department or
  // category was deleted. Render a useful fallback instead of throwing.
  const department = typeof procedure.department === "object" ? procedure.department?.name ?? "Département non attribué" : "Département non attribué";
  const category = typeof procedure.category === "object" ? procedure.category?.name ?? "Catégorie non attribuée" : "Catégorie non attribuée";
  const isAdmin = role === Role.SUPER_ADMIN;
  const isStudent = role === Role.STUDENT;
  const statusData = [
    ["Statut", <StatusBadge key="status" status={procedure.status} />], ["Version", `v${procedure.versionNumber}`], ["Prise d’effet", readableDate(procedure.effectiveDate)],
    ["Mis à jour", readableDate(procedure.lastUpdate)], ["Consultations", String(procedure.viewCount)],
  ].filter(([, value]) => Boolean(value));
  const summary = [["Statut", procedure.status], ["Version", `v${procedure.versionNumber}`], ["Département", department], ["Catégorie", category], ["Responsable", procedure.responsiblePerson], ["Prise d’effet", readableDate(procedure.effectiveDate)], ["Dernière mise à jour", readableDate(procedure.lastUpdate)], ["Vues", String(procedure.viewCount)]].filter(([, value]) => Boolean(value));

  if (isStudent) {
    return <div className="mx-auto max-w-5xl space-y-6 page-enter"><header className="border-b border-slate-200 pb-6 dark:border-slate-800"><button className="text-sm text-slate-400 hover:text-primary" onClick={() => navigate("/procedures")}>← Back to procedures</button><p className="mt-5 text-sm font-semibold text-primary">{category}</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-secondary dark:text-white">{procedure.title}</h1><p className="mt-3 max-w-3xl text-slate-600 dark:text-slate-300">{procedure.description}</p><div className="mt-5 flex flex-wrap gap-2"><ChecklistButton procedureId={procedure._id} status={procedure.status} role={role} /><Button variant="ghost" onClick={() => navigate(`/procedures/${procedure._id}`)}>Procedure overview</Button></div></header><div className="grid gap-6 lg:grid-cols-[1fr_280px]"><main className="space-y-6"><Card className="p-6"><h2 className="text-lg font-semibold text-secondary dark:text-white">What you need</h2>{procedure.requiredDocuments.length ? <ul className="mt-4 space-y-2 text-sm text-slate-600 dark:text-slate-300">{procedure.requiredDocuments.map((document) => <li key={document}>• {document}</li>)}</ul> : <p className="mt-3 text-sm text-slate-500">No required documents are specified.</p>}</Card><Card className="p-6"><h2 className="text-lg font-semibold text-secondary dark:text-white">Steps</h2>{procedure.steps.length ? <ol className="mt-5 space-y-4">{[...procedure.steps].sort((a, b) => a.order - b.order).map((step) => <li key={step.order} className="flex gap-3 text-sm text-slate-600 dark:text-slate-300"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary-50 text-xs font-bold text-primary dark:bg-primary/10">{step.order}</span><span className="pt-1"><LinkifiedText text={step.description} /></span></li>)}</ol> : <p className="mt-3 text-sm text-slate-500">No steps are specified.</p>}</Card><AttachmentsCard procedureId={procedure._id} isAdmin={false} /><ProcedureRecommendations procedureId={procedure._id} /><AiAssistantCard procedureId={procedure._id} /></main><aside className="lg:sticky lg:top-5 lg:h-fit"><Card className="p-5"><h2 className="font-semibold text-secondary dark:text-white">Important information</h2><dl className="mt-4 space-y-4"><div><dt className="text-xs text-slate-400">Department</dt><dd className="mt-1 text-sm font-medium text-secondary dark:text-slate-200">{department}</dd></div><div><dt className="text-xs text-slate-400">Effective date</dt><dd className="mt-1 text-sm font-medium text-secondary dark:text-slate-200">{readableDate(procedure.effectiveDate)}</dd></div>{procedure.deadline && <div><dt className="text-xs text-slate-400">Deadline</dt><dd className="mt-1 text-sm font-medium text-secondary dark:text-slate-200">{readableDate(procedure.deadline)}</dd></div>}</dl></Card></aside></div></div>;
  }

  return <div className="mx-auto max-w-7xl space-y-6 page-enter">
    <header className="border-b border-slate-200 pb-6 dark:border-slate-800"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-start"><div className="min-w-0"><nav aria-label="Fil d’Ariane" className="mb-4 text-xs text-slate-400"><button className="hover:text-primary focus-ring" onClick={() => navigate("/procedures")}>Procédures</button>{department && <> <span aria-hidden="true">/</span> <span>{department}</span></>} <span aria-hidden="true">/</span> <span className="text-slate-500">{procedure.title}</span></nav><h1 className="text-3xl font-bold tracking-tight text-secondary dark:text-white">{procedure.title}</h1><div className="mt-3 flex flex-wrap items-center gap-x-3 gap-y-2 text-sm text-slate-500"><span>{department}</span>{category && <><span aria-hidden="true">·</span><span>{category}</span></>}<span aria-hidden="true">·</span><span>Responsable : {procedure.responsiblePerson}</span><span aria-hidden="true">·</span><span>v{procedure.versionNumber}</span><StatusBadge status={procedure.status} /></div></div><div className="flex shrink-0 flex-wrap gap-2"><Button variant="ghost" onClick={() => navigate(-1)}>← Retour</Button><ChecklistButton procedureId={procedure._id} status={procedure.status} role={role} /><WorkflowActions procedure={procedure} role={role} onModify={() => navigate(`/procedures/${procedure._id}`)} /></div></div></header>
    <section aria-label="Informations du document" className="grid divide-y divide-slate-100 overflow-hidden rounded-xl border border-slate-200 bg-white sm:grid-cols-5 sm:divide-x sm:divide-y-0 dark:border-slate-800 dark:bg-slate-900 dark:divide-slate-800">{statusData.map(([label, value]) => <div key={String(label)} className="px-4 py-3"><p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-slate-400">{label}</p><div className="mt-1 text-sm font-medium text-secondary dark:text-slate-100">{value}</div></div>)}</section>
    <div className="overflow-x-auto border-b border-slate-200 dark:border-slate-800"><div role="tablist" aria-label="Sections de la procédure" className="flex min-w-max gap-6">{tabs.map((item) => <button key={item.id} role="tab" aria-selected={tab === item.id} className={`border-b-2 px-1 pb-3 text-sm font-medium transition-colors focus-ring ${tab === item.id ? "border-primary text-primary" : "border-transparent text-slate-500 hover:text-secondary dark:hover:text-white"}`} onClick={() => setTab(item.id)}>{item.label}</button>)}</div></div>
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_280px]"><main role="tabpanel" className="min-w-0">
      {tab === "overview" && <div className="space-y-6"><Card className="p-6"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-400">Présentation</p><h2 className="mt-1 text-xl font-semibold text-secondary dark:text-white">À propos de cette procédure</h2><p className="mt-5 whitespace-pre-line text-sm leading-7 text-slate-600 dark:text-slate-300">{procedure.description}</p>{procedure.keywords.length > 0 && <div className="mt-6"><h3 className="text-sm font-semibold text-secondary dark:text-white">Mots-clés</h3><div className="mt-3 flex flex-wrap gap-2">{procedure.keywords.map((keyword) => <span key={keyword} className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-xs text-slate-600 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-300">{keyword}</span>)}</div></div>}</Card><Card className="p-6"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-400">En un coup d’œil</p><h2 className="mt-1 text-xl font-semibold text-secondary dark:text-white">Repères de la procédure</h2><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-5">{[["Étapes", procedure.steps.length], ["Documents requis", procedure.requiredDocuments.length], ["Version", `v${procedure.versionNumber}`], ["Statut", procedure.status], ["Prise d’effet", readableDate(procedure.effectiveDate)]].map(([label, value]) => <div key={String(label)} className="rounded-lg bg-slate-50 p-3 dark:bg-slate-800"><p className="text-[11px] text-slate-400">{label}</p><p className="mt-1 text-sm font-semibold text-secondary dark:text-white">{value}</p></div>)}</div></Card></div>}
      {tab === "steps" && <Card className="p-6"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-400">Mode opératoire</p><h2 className="mt-1 text-xl font-semibold text-secondary dark:text-white">Étapes de la procédure</h2>{procedure.steps.length === 0 ? <p className="mt-5 rounded-lg bg-slate-50 p-4 text-sm text-slate-500 dark:bg-slate-800">Aucune étape n’est définie pour cette procédure.</p> : <ol className="mt-7">{[...procedure.steps].sort((a, b) => a.order - b.order).map((step, index, all) => <li key={step.order} className="relative flex gap-4 pb-8 last:pb-0"><span className="z-10 flex h-9 w-9 shrink-0 items-center justify-center rounded-full border border-primary/20 bg-primary-50 text-xs font-bold text-primary dark:bg-primary/10">{String(step.order).padStart(2, "0")}</span>{index < all.length - 1 && <span className="absolute left-[18px] top-9 h-[calc(100%-22px)] w-px bg-slate-200 dark:bg-slate-700" />}<div className="pt-1"><h3 className="text-sm font-semibold text-secondary dark:text-white">Étape {String(step.order).padStart(2, "0")}</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300"><LinkifiedText text={step.description} /></p></div></li>)}</ol>}</Card>}
      {tab === "documents" && <AttachmentsCard procedureId={procedure._id} isAdmin={isAdmin} />}
      {tab === "versions" && <VersionHistory procedure={procedure} role={role} />}
      {tab === "validation" && <ProcedureWorkflowTimeline procedure={procedure} />}
      {tab === "recommendations" && <ProcedureRecommendations procedureId={procedure._id} />}
      {tab === "ai" && <AiAssistantCard procedureId={procedure._id} />}
    </main><aside className="lg:sticky lg:top-5 lg:h-fit"><Card className="p-5"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-400">Fiche procédure</p><h2 className="mt-1 text-lg font-semibold text-secondary dark:text-white">Informations</h2><dl className="mt-5 space-y-4">{summary.map(([label, value]) => <div key={String(label)}><dt className="text-xs text-slate-400">{label}</dt><dd className="mt-1 text-sm font-medium text-secondary dark:text-slate-200">{value}</dd></div>)}</dl>{procedure.createdBy && <div className="mt-4 border-t border-slate-100 pt-4 dark:border-slate-800"><p className="text-xs text-slate-400">Créateur</p><p className="mt-1 break-all text-xs text-slate-500">{procedure.createdBy}</p></div>}</Card></aside></div>
  </div>;
}
