import { ChangeType, ProcedureStatus, Role } from "@epms/shared";
import { ApiError } from "../utils/ApiError";
import { procedureRepository } from "../repositories/procedure.repository";
import { procedureVersionRepository } from "../repositories/procedureVersion.repository";
function bump(version:string, type:ChangeType){ const [major,minor]=version.split(".").map(Number); return type===ChangeType.MAJOR?`${major+1}.0`:`${major}.${minor+1}`; }
export const procedureVersionService = {
 async createSnapshot(id:string, actor:string, changeType:ChangeType=ChangeType.MINOR, changeDescription="Publication de la procédure"){ const p=await procedureRepository.findById(id); if(!p) throw ApiError.notFound("Procedure not found"); const latest=await procedureVersionRepository.latest(id); const versionNumber=latest?bump(latest.versionNumber,changeType):"1.0"; const version=await procedureVersionRepository.create({procedureId:id,versionNumber,title:p.title,description:p.description,department:p.department,category:p.category,steps:p.steps,keywords:p.keywords,requiredDocuments:p.requiredDocuments,status:ProcedureStatus.PUBLISHED,createdBy:actor,changeType,changeDescription} as never); await procedureRepository.updateById(id,{versionNumber} as never); return version; },
 async list(id:string, role:Role){ await procedureRepository.findById(id).then(p=>{if(!p) throw ApiError.notFound("Procedure not found"); if(role!==Role.SUPER_ADMIN&&p.status!==ProcedureStatus.PUBLISHED) throw ApiError.notFound("Procedure not found");}); return procedureVersionRepository.list(id); },
 async detail(id:string,versionId:string,role:Role){ await this.list(id,role); const v=await procedureVersionRepository.detail(id,versionId); if(!v) throw ApiError.notFound("Version not found"); return v; },
 async restore(id:string,versionId:string){ const v=await procedureVersionRepository.detail(id,versionId); if(!v) throw ApiError.notFound("Version not found"); return procedureRepository.updateById(id,{title:v.title,description:v.description,department:v.department,category:v.category,steps:v.steps,keywords:v.keywords,requiredDocuments:v.requiredDocuments,status:ProcedureStatus.DRAFT,lastUpdate:new Date()} as never); },
 async compare(id:string,a:string,b:string,role:Role){ const [before,after]=await Promise.all([this.detail(id,a,role),this.detail(id,b,role)]); const fields=["title","description","keywords","requiredDocuments","steps"] as const; return {before,after,changes:fields.filter(f=>JSON.stringify(before[f])!==JSON.stringify(after[f])).map(field=>({field,before:before[field],after:after[field]}))}; }
};
