import { Role } from "@epms/shared";
import { ApiError } from "../utils/ApiError";
import { procedureService } from "./procedure.service";
import { feedbackCategories, feedbackStatuses, ProcedureFeedbackModel } from "../models/ProcedureFeedback.model";

function validate(input: any) { if (!Number.isInteger(input.rating) || input.rating < 1 || input.rating > 5) throw ApiError.badRequest("Rating must be between 1 and 5"); if (input.category && !feedbackCategories.includes(input.category)) throw ApiError.badRequest("Invalid feedback category"); if (input.comment && String(input.comment).trim().length > 500) throw ApiError.badRequest("Feedback comment cannot exceed 500 characters"); }
export const procedureFeedbackService = {
  async mine(studentId: string, procedureId: string) { await procedureService.getById(procedureId, false, Role.STUDENT); return ProcedureFeedbackModel.findOne({ student: studentId, procedure: procedureId }); },
  async save(studentId: string, procedureId: string, input: any) { const procedure = await procedureService.getById(procedureId, false, Role.STUDENT); validate(input); const update = { rating: input.rating, category: input.category || undefined, comment: String(input.comment || "").trim() || undefined, procedureVersion: procedure.versionNumber, status: "NEW" }; return ProcedureFeedbackModel.findOneAndUpdate({ student: studentId, procedure: procedureId }, { $set: update, $setOnInsert: { student: studentId, procedure: procedureId } }, { new: true, upsert: true, runValidators: true }); },
  async list(query: any) { const filter: any = {}; if (query.rating) filter.rating = Number(query.rating); if (query.category) filter.category = query.category; if (query.status) filter.status = query.status; if (query.days) filter.createdAt = { $gte: new Date(Date.now() - Number(query.days) * 86400000) }; const rows = await ProcedureFeedbackModel.find(filter).populate("procedure", "title versionNumber").populate("student", "fullName email").sort({ createdAt: -1 }).limit(200); const term = String(query.search || "").toLowerCase(); return term ? rows.filter((row: any) => row.procedure?.title?.toLowerCase().includes(term) || row.comment?.toLowerCase().includes(term)) : rows; },
  async summary() { const rows = await ProcedureFeedbackModel.find(); const total = rows.length; const average = total ? rows.reduce((sum, row) => sum + row.rating, 0) / total : null; const needsAttention = rows.filter((row) => row.status === "ACTION_REQUIRED" || row.rating <= 2).length; return { total, averageRating: average, needsAttention, proceduresReviewed: new Set(rows.map((row) => row.procedure.toString())).size }; },
  async setStatus(id: string, status: string) { if (!feedbackStatuses.includes(status as any)) throw ApiError.badRequest("Invalid feedback status"); const feedback = await ProcedureFeedbackModel.findByIdAndUpdate(id, { status }, { new: true }); if (!feedback) throw ApiError.notFound("Feedback not found"); return feedback; },
};
